export const routesPaths = {
  login: '/',
  shareData: '/share-data',
  takePhoto: '/take-photo',
  documentScan: '/document-scan',
  incorrectData: '/incorrect-data',
  errorPhotoResult: '/photo-result-error',
  repeatErrorPhotoResult: '/repeat-photo-result-error',
  scanError: '/scan-error',
  documentFields: '/document-fields',
  phoneNumber: '/phone',
  phoneError: '/phone-error',
  passSuccess: '/pass-success',
  searchChosen: '/search-chosen',
  foundFace: '/found-face',
  cardTakeAway: '/take-away',
};
